export const SEED_PROMPTS = {
  ssb: [
    { word: "Leadership", themes: ["leadership", "authority"], difficulty: 1 },
    { word: "Courage", themes: ["courage", "risk"], difficulty: 1 },
    { word: "Failure", themes: ["failure", "resilience"], difficulty: 2 },
    { word: "Discipline", themes: ["discipline", "responsibility"], difficulty: 1 },
    { word: "War", themes: ["conflict", "courage"], difficulty: 2 },
    { word: "Sacrifice", themes: ["sacrifice", "duty"], difficulty: 2 },
    { word: "Team", themes: ["teamwork", "cooperation"], difficulty: 1 },
    { word: "Nation", themes: ["patriotism", "duty"], difficulty: 1 },
    { word: "Obstacle", themes: ["resilience", "determination"], difficulty: 2 },
    { word: "Victory", themes: ["success", "determination"], difficulty: 1 },
    { word: "Duty", themes: ["duty", "responsibility"], difficulty: 1 },
    { word: "Honor", themes: ["honor", "duty"], difficulty: 1 },
    { word: "Soldier", themes: ["duty", "sacrifice"], difficulty: 1 },
    { word: "Challenge", themes: ["resilience", "determination"], difficulty: 2 },
    { word: "Unity", themes: ["teamwork", "cooperation"], difficulty: 1 },
    { word: "Initiative", themes: ["leadership", "ambition"], difficulty: 1 },
    { word: "Responsibility", themes: ["responsibility", "leadership"], difficulty: 1 },
    { word: "Determination", themes: ["determination", "resilience"], difficulty: 1 },
  ],
  interview: [
    { word: "Success", themes: ["ambition", "leadership"], difficulty: 1 },
    { word: "Weakness", themes: ["self-awareness", "growth"], difficulty: 2 },
    { word: "Teamwork", themes: ["teamwork", "cooperation"], difficulty: 1 },
    { word: "Deadline", themes: ["discipline", "pressure"], difficulty: 2 },
    { word: "Innovation", themes: ["creativity", "leadership"], difficulty: 1 },
    { word: "Conflict", themes: ["conflict", "resolution"], difficulty: 2 },
    { word: "Growth", themes: ["growth", "ambition"], difficulty: 1 },
    { word: "Criticism", themes: ["resilience", "self-awareness"], difficulty: 2 },
    { word: "Pressure", themes: ["pressure", "resilience"], difficulty: 2 },
    { word: "Opportunity", themes: ["ambition", "growth"], difficulty: 1 },
    { word: "Collaboration", themes: ["teamwork", "communication"], difficulty: 1 },
    { word: "Mistake", themes: ["failure", "learning"], difficulty: 2 },
    { word: "Feedback", themes: ["communication", "growth"], difficulty: 1 },
    { word: "Goal", themes: ["ambition", "discipline"], difficulty: 1 },
    { word: "Ownership", themes: ["responsibility", "leadership"], difficulty: 1 },
  ],
  student: [
    { word: "Exam", themes: ["discipline", "resilience"], difficulty: 1 },
    { word: "Dream", themes: ["ambition", "growth"], difficulty: 1 },
    { word: "Focus", themes: ["discipline", "self-control"], difficulty: 1 },
    { word: "Hardwork", themes: ["determination", "success"], difficulty: 1 },
    { word: "Friend", themes: ["empathy", "cooperation"], difficulty: 1 },
    { word: "Future", themes: ["growth", "optimism"], difficulty: 1 },
    { word: "Failure", themes: ["learning", "resilience"], difficulty: 2 },
    { word: "Doubt", themes: ["self-awareness", "courage"], difficulty: 2 },
    { word: "Curiosity", themes: ["learning", "creativity"], difficulty: 1 },
    { word: "Time", themes: ["discipline", "management"], difficulty: 1 },
    { word: "Teacher", themes: ["guidance", "respect"], difficulty: 1 },
    { word: "Respect", themes: ["respect", "cooperation"], difficulty: 1 },
  ],
  workplace: [
    { word: "Strategy", themes: ["leadership", "vision"], difficulty: 1 },
    { word: "Delegation", themes: ["trust", "management"], difficulty: 2 },
    { word: "Ethics", themes: ["integrity", "responsibility"], difficulty: 1 },
    { word: "Change", themes: ["adaptability", "resilience"], difficulty: 2 },
    { word: "Customer", themes: ["empathy", "service"], difficulty: 1 },
    { word: "Crisis", themes: ["composure", "problem-solving"], difficulty: 2 },
    { word: "Execution", themes: ["agency", "action"], difficulty: 1 },
    { word: "Productivity", themes: ["efficiency", "focus"], difficulty: 1 },
    { word: "Alignment", themes: ["collaboration", "vision"], difficulty: 1 },
    { word: "Risk", themes: ["decision-making", "courage"], difficulty: 2 },
    { word: "Accountability", themes: ["ownership", "integrity"], difficulty: 1 },
    { word: "Culture", themes: ["community", "values"], difficulty: 1 },
  ],
};
